version: '3.8'
services:
  extractor:
    build:
      context: ./services/api_data_extractor
      dockerfile: Dockerfile
    environment:
      UVICORN_SERVER_PORT: "8080"
      API_PREFIX: "/extractor/api"
      WORKERS_COUNT: "1"
    command: bash entrypoint.sh
    ports:
      - "8081:8080"
  filter:
    build:
      context: ./services/api_data_filter
      dockerfile: Dockerfile
    environment:
      UVICORN_SERVER_PORT: "8080"
      API_PREFIX: "/filter/api"
      WORKERS_COUNT: "1"
    command: bash entrypoint.sh
    ports:
      - "8082:8080"
  receiver:
    build:
      context: ./services/api_data_receiver
      dockerfile: Dockerfile
    environment:
      UVICORN_SERVER_PORT: "8080"
      API_PREFIX: "/receiver/api"
      WORKERS_COUNT: "1"
    command: bash entrypoint.sh
    ports:
      - "8083:8080"